name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  mac-os:
    runs-on: macos-14
    steps:
      - name: select Xcode
        run: |
          sudo xcode-select --switch "/Applications/Xcode_15.2.app"
      - uses: actions/checkout@v4
      - name: Make test
        run: make test
